name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Setup node 
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install
      - run: npm run test 

      - name: Generate tag 
        id: generate_tag
        run: | 
          SHA=$(echo $GITHUB_SHA | head -c7) 
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: docker build -t fernandafmsf/rocketseat-ci-api:${{steps.generate_tag.outputs.sha}} . ## vai buildar a imagem com a tag gerada no passo anterior

      - name: Push Docker Image
        run: docker push fernandafmsf/rocketseat-ci-api:${{steps.generate_tag.outputs.sha}}
